import {Accessor, JSX, on} from "solid-js";
import { Color, ColorScale } from "../ColorScale";
import {type ForecastMetadata} from "../data/ForecastMetadata";
import {DetailedForecast, LocationForecasts} from "../data/LocationForecasts";
import {type Zone} from "../data/Model";

type Summarizer = {
  /** Create a summary of the forecast data on the point (shown in popups) */
  summary(lat: number, lng: number): Promise<[LocationForecasts, Array<[Accessor<string>, JSX.Element]> | undefined] | undefined>
}

// Non-static parts of layers
export type ReactiveComponents = {
  /** The current summarizer (shown in popups) of a layer. */
  readonly summarizer: Accessor<Summarizer>
  /** The map key of the layer. */
  readonly mapKey: JSX.Element
  /** The documentation of the layer (shown in the help modal). */
  readonly help: JSX.Element
}

/**
 * A layer shown over the map (boundary layer height, cloud cover, etc.)
 */
 export type Layer = {
  readonly key: string
  readonly name: Accessor<string>
  readonly title: Accessor<string>
  readonly dataPath: string
  /** WebGL style expression for rendering the COG raster on the map (TODO introduce on RasterLayer only) */
  readonly webglStyle: object
  reactiveComponents(props: {
    forecastMetadata: ForecastMetadata,
    zone: Zone,
    hourOffset: number,
    windNumericValuesShown: boolean,
    timeZone: string | undefined,
    setHourOffset: (value: number) => void
  }): ReactiveComponents
}

export const colorScaleEl = (colorScale: ColorScale, format: (value: number) => string): JSX.Element => {
  const colorsAndValues: Array<[Color, string]> = colorScale.points.slice().reverse().map(([value, color]) => [color, format(value)]);
  const length = colorsAndValues.reduce((n, [_, s]) => s.length > n ? s.length : n, 0);
  return <div style={{ width: `${length * 2 / 3}em`, 'padding-top': '0.3em' /* because text overflows */, margin: 'auto' }}>
  {
    colorsAndValues.map(([color, value]) =>
      <div style={{ height: '2em', opacity: 0.7, 'background-color': color.css(), position: 'relative' }}>
        <span style={{ position: 'absolute', top: '-.6em', right: '0.5em', 'text-shadow': 'white 1px 1px 2px' }}>{value}</span>
      </div>
    )
  }
  </div>
};

 export const summarizerFromLocationDetails = (props: {
  zone: Zone,
  forecastMetadata: ForecastMetadata,
  hourOffset: number
}, summary: (detailedForecast: DetailedForecast, locationForecasts: LocationForecasts) => Array<[Accessor<string>, JSX.Element]>) => {
  return (): Summarizer => {
    // Make our dependencies explicit because accessing them from the summary method would be outside the tracking scope
    on(
      [
        () => props.forecastMetadata,
        () => props.hourOffset,
        () => props.zone
      ],
      () => {}
    )();
    return {
      async summary(lat: number, lng: number): Promise<[LocationForecasts, Array<[Accessor<string>, JSX.Element]> | undefined] | undefined> {
        const locationForecasts = await props.forecastMetadata.fetchLocationForecasts(props.zone, lat, lng);
        if (locationForecasts === undefined) {
          return undefined
        }
        const detailedForecast = locationForecasts.atHourOffset(props.hourOffset);
        if (detailedForecast === undefined) {
          return [locationForecasts, undefined]
        } else {
          return [locationForecasts, summary(detailedForecast, locationForecasts)]
        }
      }
    }
  }
}

/**
 * Converts a ColorScale into an OpenLayers WebGL style object.
 *
 * When the GeoTIFF source has a nodata value (either from metadata or config),
 * OpenLayers adds an alpha band (band 2): 0 for NODATA/padding pixels, 255 for
 * valid data. The custom `color` expression fully replaces the pixel output, so
 * we must check band 2 explicitly — it is NOT applied automatically.
 */
export const colorScaleToWebGLStyle = (colorScale: ColorScale): object => {
  const cases: any[] = [
    // NODATA pixels: the alpha band generated by the GeoTIFF source is 0
    ['==', ['band', 2], 0],
    [0, 0, 0, 0],
  ];
  for (const [value, color] of colorScale.points) {
    cases.push(['<', ['band', 1], value]);
    cases.push([color.red, color.green, color.blue, color.opacity]);
  }
  return {
    color: [
      'case',
      ...cases,
      [0, 0, 0, 0] // fallback: transparent
    ]
  };
};
